export type BundledTtsAsset = {
  module: number;
  relativePath: string;
};

// Generated by scripts/convert_twi_tts.py when model assets are available.
export const bundledTtsAssets: BundledTtsAsset[] = [];